apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blogs-app-ingress
spec:
  rules:
    - host: www.blogsapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 3000
          - path: /api 
            pathType: Prefix
            backend:
              service:
                name: server-service
                port:
                  number: 8000

